#!/usr/bin/python3
# -*- coding:utf-8 -*-
import sys
import os
import requests
import logging
import time

indelay = input("Enter Delay in Mins: ")

#*****************EVENT1*****************
requests.post('https://maker.ifttt.com/trigger/"EVENT""/with/key/""IFTTTKEY"')  #*****Replace EVENT and IFTTTKEY with IFTTT credentials NO QUOTES

delay = indelay * 60
iDelay = delay
i = 0
while (i<=delay):
   vDelay = time.strftime('%M:%S', time.gmtime(iDelay))
   print(vDelay)
   i += 1
   iDelay -= 1
   time.sleep(1)

#*****************EVENT2*****************
requests.post('https://maker.ifttt.com/trigger/"EVENT""/with/key/""IFTTTKEY"')  #*****Replace EVENT and IFTTTKEY with IFTTT credentials NO QUOTES

print("Complete")
